In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
Education = pd.read_csv('../1data/KSPS/UNHCR-KEN-2018-SEA-Kalobeyei-Education.csv')
Energy = pd.read_csv('../1data/KSPS/UNHCR-KEN-2018-SEA-Kalobeyei-Energy.csv')           
Food = pd.read_csv('../1data/KSPS/UNHCR-KEN-2018-SEA-Kalobeyei-Food.csv')            
Household = pd.read_csv('../1data/KSPS/UNHCR-KEN-2018-SEA-Kalobeyei-Household.csv') 
Member = pd.read_csv('../1data/KSPS/UNHCR-KEN-2018-SEA-Kalobeyei-Member.csv')
Nonfood = pd.read_csv('../1data/KSPS/UNHCR-KEN-2018-SEA-Kalobeyei-Nonfood.csv')

In [3]:
#Food Rename
Food= Food.rename(columns={"s12q1":"hh_purchasedfood7d", "s12q2":"amountfood_purchased7d", 
                     "s12q4":"foodspent_localcurrecny", "s12q6": "foodconsumed7d","s12q7": "foodwasfree", 
                     "cons_q_kg": "quantityfood_consumedkg", 
                     "cons_q_kg_pc": "quantityfood_consumedkg_pc"})

In [4]:
Food = Food.drop(["mod_opt", "item_id", "item_name", "s12q2_a", 
                  "s12q6_1", "purc_conv2kg",
                  "national_uv_2015_16", "purc_uv_med_2018_19", "cons_conv2kg", 
                  "purc_uv"], axis=1)

In [5]:
Food['Dataset1'] = "Food"

In [6]:
#Household Rename 
Household= Household.rename(columns={"s6q1": "number_dwellings", "s6q2": "number_habitablerooms", 
                          "s6q3":"floor_material", "s6q4":"roof_material", "s6q5":"wall_material",
                          "s6q6":"drikingwater_source", "s6q7": "drinkingwater_insufficientquanities", 
                          "s6q8": "toilet_type", "s6q9": "share_toilet", "s6q11": "lighting_source", 
                          "s6q13": "payrent_dwelling", "s6q14": "rentpaid_shillings", "s7q1": "own_radio",
                          "s7q2": "own_television", "s7q3": "own_satelitedish", "s7q4": "own_smartphone",
                          "s7q5":"own_refrigerator", "s7q6": "own_table", "s7q7": "own_bed", "s7q8": "own_mattress", 
                          "s7q9":"own_mosquitonet", "s7q10":"own_fan", "s7q11": "own_bicycle", "s7q12":"own_motorcycle", 
                          "s7q13": "own_car", "s7q14": "own_generator", "s7q15": "own_solarpanels", "s7q16": "own_kerosenestove",
                          "s7q17": "own_charcoaljiko", "s7q18": "own_wheelbarrow", "s7q19": "own_ironfencing", 
                          "s7q20": "own_farmanimals", "s8q1": "relatives_abroad", "s8q2": "relatives_outsidekenya", 
                          "s8q3": "own_bankaccount", "s8q4": "borrowedfrom_sources12mo", "s8q4_1": "borrowedfrom_bank12mo", 
                          "s8q4_2": "borrowedfrom_community", "s8q4_3": "borrowedfrom_familyorfriends12mo", "s8q5": "remittances_abroad", 
                          "s8q6": "purchased_insurance", "s9q1":"childunder5_death5yrs", "s11q1": "sellhhgoods_lackfood", 
                          "s11q2": "healthandeduc_reduction", "s11q3": "sellassets_lackfood", "s11q4": "spendsavings:lackfood", 
                         "s11q5": "borrowmoneyfood_lackfood", "s11q6": "sellhouseland_lackfood", "s11q7": "withdrawchildrenschool_lackfood", 
                         "s11q8":"sellanimals:lackfood", "s11q9": "sellfemaleanimal_last", "s11q10": "beg_lackfood"})

In [7]:
Household= Household.drop(["s1q5", "s10q1", "s10q2", "s10q3", "s10q4", "s10q5",
                           "s10q6", "s10q7", "s10q8", "s10q9", "s11q1_a", "s11q2_a", 
                          "s11q3_a", "s11q4_a", "s11q4_a", "s11q5_a", "s11q6_a", "s11q7_a", 
                          "s11q8_a", "s11q9_a", "s11q10_a"], axis=1)

In [8]:
Household['Dataset2'] = "Household"

In [9]:
#Energy Rename
Energy = Energy.rename(columns={"s1q2":"hhlocation", "s12q12a":"q_purchased_firewoodused", 
                       "s12q12b": "totalcost_purchasedfirewood",
                     "s12q13a": "q_collected_firewoodused","s12q13b": "totalcost_collectedfirewood",
                      "s12q14a": "q_farmresidue_used", "s12q14b": 'totalcost_farmresidue',
                      's12q15a':'q_wood/processwaste_used', 's12q15b': 'totalcost_wood/processwaste',
                      's12q16a': 'q_charcoal_used', 's12q16b': 'totalcost_charcoal',
                      's12q17a': 'q_kerosene/paraffin_used', 's12q17b': 'totalcost_kerosene/paraffin',
                      's12q18a': 'q_lpg_used', 's12q18b': 'totalcost_lpg', 
                      's12q19a': 'q_electricity_used', 's12q19b': 'totalcost_electricity',
                      's12q20a': 'q_petrol_used', 's12q20b': 'totalcost_petrol',
                       's12q21a': 'q_diesel_used', 's12q21b': 'totalcost_diesel'})

In [10]:
Energy = Energy.drop(['s12q12', 's12q12a_1', 's12q13', 's12q13a_1', 's12q14', 's12q14a_1',
            's12q15', 's12q15a_1', 's12q16', 's12q16a_1', 's12q17', 's12q18'], axis = 1)

In [11]:
Energy['Dataset3'] = "Energy"

In [12]:
#Education Rename
Education = Education.rename(columns={'s4q10': 'spend_tuitionfees', 's4q11': 'spend_textbooks', 
                         's4q12': 'spend_exercisebooks', 's4q13': 'spend_schooluniform',
                         's4q14': 'spend_schoolboardingfees', 's4q15': 'spend_schooltransport',
                         's4q16': 'spend_extratuition', 's4q17': 'spend_PTA', 
                         's4q18': 'spend_pocketmoney', 's4q19': 'spend_cautionmoney',
                         's4q20': 'spend_educmedicalfee', 's4q21': 'spend_activityfees',
                         's4q22': 'spend_examfees', 's4q23': 'spend_educfeedingprogram',
                         's4q24': 'spend_othereduccharges'})

In [13]:
#Nonfood Rename
Nonfood = Nonfood.rename(columns={"s1q2":"hhlocation", 
                        "s12q9":"purchased", 
                        "s12q10": "cost"})

In [14]:
Nonfood['Dataset5'] = "Nonfood"

In [15]:
Education['Dataset4'] = "Education"

In [16]:
Educ_Energy_merge = pd.merge(Education,Energy,how='inner',on='hhid')

In [17]:
Educ_Energy_Food_merge =  pd.merge(Educ_Energy_merge,Food,how='inner',on='hhid')

In [18]:
Educ_Energy_Food_Nonfood_merge = pd.merge(Educ_Energy_Food_merge,Nonfood,how='inner',on='hhid')

In [19]:
Merge_Renamed = pd.merge(Educ_Energy_Food_Nonfood_merge,Household,how='inner',on='hhid')

In [20]:
Merge_Renamed

,hhid,s1q2_x,spend_tuitionfees,spend_textbooks,spend_exercisebooks,spend_schooluniform,spend_schoolboardingfees,spend_schooltransport,spend_extratuition,spend_PTA,...,hh_con,hh_con2011,hh_con2011_pd,pline_ipl,poorIPL,pgi,spg,weight,popweight_y,Dataset2
0,10,Village 1,0.0,0.0,2400.000000,0.0,6000.0,3000.0,2000.000061,0.0,...,4679.5698,82.809280,2.722497,1.9,Non-poor,0.000000,0.000000,5.557168,27.785843,Household
1,10,Village 1,0.0,0.0,2400.000000,0.0,6000.0,3000.0,2000.000061,0.0,...,4679.5698,82.809280,2.722497,1.9,Non-poor,0.000000,0.000000,5.557168,27.785843,Household
2,10,Village 1,0.0,0.0,2400.000000,0.0,6000.0,3000.0,2000.000061,0.0,...,4679.5698,82.809280,2.722497,1.9,Non-poor,0.000000,0.000000,5.557168,27.785843,Household
3,10,Village 1,0.0,0.0,2400.000000,0.0,6000.0,3000.0,2000.000061,0.0,...,4679.5698,82.809280,2.722497,1.9,Non-poor,0.000000,0.000000,5.557168,27.785843,Household
4,10,Village 1,0.0,0.0,2400.000000,0.0,6000.0,3000.0,2000.000061,0.0,...,4679.5698,82.809280,2.722497,1.9,Non-poor,0.000000,0.000000,5.557168,27.785843,Household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551281,6004,Village 3,0.0,0.0,1000.000031,0.0,0.0,0.0,0.000000,0.0,...,2143.0713,37.923611,1.246804,1.9,Poor,0.355312,0.126247,5.557168,66.686020,Household
551282,6004,Village 3,0.0,0.0,1000.000031,0.0,0.0,0.0,0.000000,0.0,...,2143.0713,37.923611,1.246804,1.9,Poor,0.355312,0.126247,5.557168,66.686020,Household
551283,6004,Village 3,0.0,0.0,1000.000031,0.0,0.0,0.0,0.000000,0.0,...,2143.0713,37.923611,1.246804,1.9,Poor,0.355312,0.126247,5.557168,66.686020,Household
551284,6004,Village 3,0.0,0.0,1000.000031,0.0,0.0,0.0,0.000000,0.0,...,2143.0713,37.923611,1.246804,1.9,Poor,0.355312,0.126247,5.557168,66.686020,Household
551285,6004,Village 3,0.0,0.0,1000.000031,0.0,0.0,0.0,0.000000,0.0,...,2143.0713,37.923611,1.246804,1.9,Poor,0.355312,0.126247,5.557168,66.686020,Household

In [ ]:
#Merge_Renamed.to_excel('MergedDatasetsRenamed_F.xlsx',sheet_name='Sheet1')

In [21]:
Merge_Renamed.to_excel('MergedDatasetsRenamed_T.xlsx',sheet_name='Sheet1')

FileSizeError: Filesize would require ZIP64 extensions. Use workbook.use_zip64().