In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV

from sklearn.metrics import mean_squared_error
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import GridSearchCV

In [ ]:
FinalMerge = pd.read_excel('../2progs/Excel_Files/C3_FinalMerge.xlsx',sheet_name='Sheet1',index_col = 0)

In [3]:
#converting to floats
FinalMerge['number_dwellings'] = FinalMerge['number_dwellings'].astype(float)
FinalMerge['number_habitablerooms'] = FinalMerge['number_habitablerooms'].astype(float)
FinalMerge['share_toilet_Yes'] = FinalMerge['share_toilet_Yes'].astype(float)
FinalMerge['own_radio_Yes'] = FinalMerge['own_radio_Yes'].astype(float)
FinalMerge['own_television_Yes'] = FinalMerge['own_television_Yes'].astype(float)
FinalMerge['own_satelitedish_Yes'] = FinalMerge['own_satelitedish_Yes'].astype(float)
FinalMerge['own_smartphone_Yes'] = FinalMerge['own_smartphone_Yes'].astype(float)
FinalMerge['own_refrigerator_Yes'] = FinalMerge['own_refrigerator_Yes'].astype(float)
FinalMerge['own_table_Yes'] = FinalMerge['own_table_Yes'].astype(float)
FinalMerge['own_bed_Yes'] = FinalMerge['own_bed_Yes'].astype(float)
FinalMerge['own_mattress_Yes'] = FinalMerge['own_mattress_Yes'].astype(float)
FinalMerge['own_mosquitonet_Yes'] = FinalMerge['own_mosquitonet_Yes'].astype(float)
FinalMerge['own_mattress_Yes'] = FinalMerge['own_mattress_Yes'].astype(float)
FinalMerge['own_fan_Yes'] = FinalMerge['own_fan_Yes'].astype(float)
FinalMerge['own_bicycle_Yes'] = FinalMerge['own_bicycle_Yes'].astype(float)
FinalMerge['own_motorcycle_Yes'] = FinalMerge['own_motorcycle_Yes'].astype(float)
FinalMerge['own_generator_Yes'] = FinalMerge['own_generator_Yes'].astype(float)
FinalMerge['own_solarpanels_Yes'] = FinalMerge['own_solarpanels_Yes'].astype(float)
FinalMerge['own_kerosenestove_Yes'] = FinalMerge['own_kerosenestove_Yes'].astype(float)
FinalMerge['own_charcoaljiko_Yes'] = FinalMerge['own_charcoaljiko_Yes'].astype(float)
FinalMerge['own_wheelbarrow_Yes'] = FinalMerge['own_wheelbarrow_Yes'].astype(float)
FinalMerge['own_ironfencing_Yes'] = FinalMerge['own_ironfencing_Yes'].astype(float)
FinalMerge['own_farmanimals_Yes'] = FinalMerge['own_farmanimals_Yes'].astype(float)
FinalMerge['hh_purchasedfood7d_Yes'] = FinalMerge['own_farmanimals_Yes'].astype(float)
FinalMerge['foodwasfree_Yes'] = FinalMerge['own_farmanimals_Yes'].astype(float)

#for own_car variable, all of them were a no, so they were dropped

#Rest of float variables for the unrestricted dataset 
FinalMerge['headFemale'] = FinalMerge['headFemale'].astype(float)
FinalMerge['size'] = FinalMerge['size'].astype(float)
FinalMerge['shareWithEarlyChildhood'] = FinalMerge['shareWithEarlyChildhood'].astype(float)
FinalMerge['issue'] = FinalMerge['issue'].astype(float)
FinalMerge['foodspent_localcurrecny'] = FinalMerge['foodspent_localcurrecny'].astype(float)
FinalMerge['familysize1'] = FinalMerge['familysize1'].astype(float)
FinalMerge['familysize2'] = FinalMerge['familysize2'].astype(float)
FinalMerge['familysize3'] = FinalMerge['familysize3'].astype(float)
FinalMerge['familysize4'] = FinalMerge['familysize4'].astype(float)
FinalMerge['familysize5'] = FinalMerge['familysize5'].astype(float)
FinalMerge['floor_material'] = FinalMerge['floor_material'].astype(float)
FinalMerge['roof_material'] = FinalMerge['roof_material'].astype(float)
FinalMerge['toilet_type'] = FinalMerge['toilet_type'].astype(float)
FinalMerge['lighting_source'] = FinalMerge['lighting_source'].astype(float)
FinalMerge['rentpaid_shillings'] = FinalMerge['rentpaid_shillings'].astype(float)
FinalMerge['relatives_abroad_Yes'] = FinalMerge['relatives_abroad_Yes'].astype(float)
FinalMerge['borrowedfrom_sources12mo_Yes'] = FinalMerge['borrowedfrom_sources12mo_Yes'].astype(float)
FinalMerge['borrowedfrom_bank12mo_Yes'] = FinalMerge['borrowedfrom_bank12mo_Yes'].astype(float)
FinalMerge['borrowedfrom_community_Yes'] = FinalMerge['borrowedfrom_community_Yes'].astype(float)
FinalMerge['borrowedfrom_familyorfriends12mo_Yes'] = FinalMerge['borrowedfrom_familyorfriends12mo_Yes'].astype(float)
FinalMerge['remittances_abroad_Yes'] = FinalMerge['remittances_abroad_Yes'].astype(float)
FinalMerge['purchased_insurance_Yes'] = FinalMerge['purchased_insurance_Yes'].astype(float)
FinalMerge['sellhhgoods_lackfood_Yes'] = FinalMerge['sellhhgoods_lackfood_Yes'].astype(float)
FinalMerge['withdrawchildrenschool_lackfood_Yes'] = FinalMerge['withdrawchildrenschool_lackfood_Yes'].astype(float)
FinalMerge['sellanimals:lackfood_Yes'] = FinalMerge['sellanimals:lackfood_Yes'].astype(float)
FinalMerge['beg_lackfood_Yes'] = FinalMerge['beg_lackfood_Yes'].astype(float)
FinalMerge['drikingwater_source'] = FinalMerge['drikingwater_source'].astype(float)
FinalMerge['crowdindex_room'] = FinalMerge['crowdindex_room'].astype(float)
FinalMerge['LCS_index'] = FinalMerge['LCS_index'].astype(float)
FinalMerge['poorIPL'] = FinalMerge['poorIPL'].astype(float)
#FinalMerge['childunder5_death5yrs'] = FinalMerge['childunder5_death5yrs'].astype(float)

In [4]:
ln_expenditure_per_capita = np.log(FinalMerge['Total_Spend']/FinalMerge['size'])

In [5]:
#would be for unrestricted set
unwanted = FinalMerge.columns[FinalMerge.columns.str.startswith('spend_')]
FinalMerge.drop(unwanted, axis=1, inplace=True)

unwanted2 = FinalMerge.columns[FinalMerge.columns.str.endswith('TotalSpend')]
FinalMerge.drop(unwanted2, axis=1, inplace=True)

unwanted3 = FinalMerge.columns[FinalMerge.columns.str.startswith('q_')]
FinalMerge.drop(unwanted3, axis=1, inplace=True)

unwanted4 = FinalMerge.columns[FinalMerge.columns.str.startswith('totalcost')]
FinalMerge.drop(unwanted4, axis=1, inplace=True)

unwanted5 = FinalMerge.columns[FinalMerge.columns.str.startswith('Dataset')]
FinalMerge.drop(unwanted5, axis=1, inplace=True)

unwanted6 = FinalMerge.columns[FinalMerge.columns.str.startswith('hhsize')]
FinalMerge.drop(unwanted6, axis=1, inplace=True)

unwanted7 = FinalMerge.columns[FinalMerge.columns.str.startswith('s1q2')]
FinalMerge.drop(unwanted7, axis=1, inplace=True)

unwanted8 = FinalMerge.columns[FinalMerge.columns.str.startswith('weight')]
FinalMerge.drop(unwanted8, axis=1, inplace=True)

unwanted9 = FinalMerge.columns[FinalMerge.columns.str.startswith('hhid')]
FinalMerge.drop(unwanted9, axis=1, inplace=True)

unwanted10 = FinalMerge.columns[FinalMerge.columns.str.startswith('popweight')]
FinalMerge.drop(unwanted10, axis=1, inplace=True)

unwanted11 = FinalMerge.columns[FinalMerge.columns.str.startswith('hhlocation')]
FinalMerge.drop(unwanted11, axis=1, inplace=True)

unwanted12 = FinalMerge.columns[FinalMerge.columns.str.startswith('improved_sanitation')]
FinalMerge.drop(unwanted12, axis=1, inplace=True)

unwanted13 = FinalMerge.columns[FinalMerge.columns.str.startswith('improved_water')]
FinalMerge.drop(unwanted13, axis=1, inplace=True)

unwanted14 = FinalMerge.columns[FinalMerge.columns.str.startswith('s1q5')]
FinalMerge.drop(unwanted14, axis=1, inplace=True)

unwanted15 = FinalMerge.columns[FinalMerge.columns.str.startswith('s12q19')]
FinalMerge.drop(unwanted15, axis=1, inplace=True)

unwanted16 = FinalMerge.columns[FinalMerge.columns.str.startswith('s12q20')]
FinalMerge.drop(unwanted16, axis=1, inplace=True)

unwanted17 = FinalMerge.columns[FinalMerge.columns.str.startswith('s12q21')]
FinalMerge.drop(unwanted17, axis=1, inplace=True)

unwanted18 = FinalMerge.columns[FinalMerge.columns.str.startswith('foodspent_localcurrecny')]
FinalMerge.drop(unwanted18, axis=1, inplace=True)

unwanted19 = FinalMerge.columns[FinalMerge.columns.str.startswith('issue')]
FinalMerge.drop(unwanted19, axis=1, inplace=True)

unwanted20 = FinalMerge.columns[FinalMerge.columns.str.startswith('cost')]
FinalMerge.drop(unwanted20, axis=1, inplace=True)

unwanted22 = FinalMerge.columns[FinalMerge.columns.str.startswith('hh_fcon')]
FinalMerge.drop(unwanted22, axis=1, inplace=True)

unwanted23 = FinalMerge.columns[FinalMerge.columns.str.startswith('hh_nfcon')]
FinalMerge.drop(unwanted23, axis=1, inplace=True)

unwanted24 = FinalMerge.columns[FinalMerge.columns.str.startswith('childunder5_death5yrs')]
FinalMerge.drop(unwanted24, axis=1, inplace=True)

#why are there variables that aren't named?
Remove_extra_vars = FinalMerge.columns[FinalMerge.columns.str.endswith('_No')]
FinalMerge.drop(Remove_extra_vars, axis=1, inplace=True)

Remove_extra_vars2 = FinalMerge.columns[FinalMerge.columns.str.endswith('_nan')]
FinalMerge.drop(Remove_extra_vars2, axis=1, inplace=True)

In [7]:
Unrestricted = pd.DataFrame(FinalMerge)
unwanted21 = Unrestricted.columns[Unrestricted.columns.str.startswith('Total_Spend')]
Unrestricted.drop(unwanted21, axis=1, inplace=True)
Unrestricted

,size,headFemale,shareFemale,shareAgeZeroToFour,shareAgeFiveToNine,shareAgeTenToFourteen,shareAgeFifteenToTwentyfour,shareAgeTwentyfivetofourtynine,shareAgeFiftyPlus,shareMaleAgeTenToNineteen,...,healthandeduc_reduction_Yes,sellassets_lackfood_Yes,spendsavings:lackfood_Yes,borrowmoneyfood_lackfood_Yes,sellhouseland_lackfood_Yes,withdrawchildrenschool_lackfood_Yes,sellanimals:lackfood_Yes,sellfemaleanimal_last_Yes,beg_lackfood_Yes,share_toilet_Yes
0,5.0,1.0,0.800000,0.200000,0.400000,0.200000,0.000000,0.200000,0.000000,0.000000,...,0,1,0,1,0,0.0,0.0,0,0.0,1.0
1,6.0,1.0,0.166667,0.000000,0.000000,0.166667,0.666667,0.166667,0.000000,0.666667,...,0,1,0,1,0,0.0,1.0,1,0.0,1.0
2,6.0,1.0,0.833333,0.166667,0.333333,0.333333,0.000000,0.166667,0.000000,0.000000,...,0,0,0,0,0,0.0,0.0,0,0.0,0.0
3,14.0,1.0,0.714286,0.285714,0.285714,0.142857,0.142857,0.071429,0.071429,0.071429,...,0,0,0,1,0,0.0,0.0,0,0.0,0.0
4,2.0,0.0,0.500000,0.000000,0.000000,0.000000,0.500000,0.500000,0.000000,0.000000,...,0,1,0,1,0,0.0,1.0,0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,15.0,1.0,0.133333,0.000000,0.133333,0.333333,0.400000,0.066667,0.066667,0.733333,...,0,0,0,0,0,0.0,0.0,0,0.0,1.0
1086,2.0,0.0,0.500000,0.000000,0.000000,0.000000,0.500000,0.500000,0.000000,0.000000,...,0,0,0,0,0,0.0,0.0,0,0.0,1.0
1087,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0,0,0,0,0,0.0,0.0,0,0.0,1.0
1088,4.0,1.0,0.750000,0.500000,0.250000,0.000000,0.000000,0.250000,0.000000,0.000000,...,0,0,0,1,0,0.0,0.0,0,0.0,0.0
1089,12.0,0.0,0.666667,0.166667,0.250000,0.166667,0.166667,0.166667,0.083333,0.166667,...,0,0,0,0,0,0.0,0.0,0,0.0,0.0

In [8]:
y = ln_expenditure_per_capita

x = Unrestricted

In [9]:
Unrestricted = Unrestricted.astype(float)

In [10]:
alphas = 10**np.linspace(10,-2,100)*0.5

In [11]:
#ridge - unrestricted
ridge = Ridge(normalize = True)
coefs = []

for a in alphas:
    ridge.set_params(alpha = a)
    ridge.fit(x, y)
    coefs.append(ridge.coef_)
    
np.shape(coefs)

(100, 87)

In [12]:
#Perform all three tests with unrestricted set
x_train, x_test , y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

In [13]:
#cross validation to choose optimal alpha
ridgecv = RidgeCV(alphas = alphas, scoring = 'neg_mean_squared_error', normalize = True)
ridgecv.fit(x_train, y_train)
ridgecv.alpha_

#Test MSE w/ optimal alpha
ridge4 = Ridge(alpha = ridgecv.alpha_, normalize = True)
ridge4.fit(x_train, y_train)

Ridge(alpha=0.5748784976988678, normalize=True)

In [14]:
# Ridge Model - Unrestricted Data Set  
#Fit ridge model w/ optimal alpha 
ridge4.fit(x, y)
pd.Series(ridge.coef_, index = x.columns)

size                                  -0.023049
headFemale                            -0.014767
shareFemale                           -0.148679
shareAgeZeroToFour                    -0.211999
shareAgeFiveToNine                    -0.057363
                                         ...
withdrawchildrenschool_lackfood_Yes   -0.005074
sellanimals:lackfood_Yes              -0.324059
sellfemaleanimal_last_Yes             -0.212360
beg_lackfood_Yes                       0.024669
share_toilet_Yes                       0.053434
Length: 87, dtype: float64

In [15]:
Y_test_ridge_ur = ridge4.predict(x_test)
ridge_unrest_coeff = pd.DataFrame()
ridge_unrest_coeff["Unrestricted Dataset Variables"] = x_train.columns 
ridge_unrest_coeff['Ridge Coefficients'] = pd.Series(ridge4.coef_)
ridge_unrest_coeff

         Unrestricted Dataset Variables  Ridge Coefficients
0                                  size           -0.020188
1                            headFemale           -0.013880
2                           shareFemale           -0.071191
3                    shareAgeZeroToFour           -0.193728
4                    shareAgeFiveToNine           -0.093385
..                                  ...                 ...
82  withdrawchildrenschool_lackfood_Yes            0.009024
83             sellanimals:lackfood_Yes           -0.183681
84            sellfemaleanimal_last_Yes           -0.154891
85                     beg_lackfood_Yes            0.014362
86                     share_toilet_Yes            0.038768

[87 rows x 2 columns]

In [18]:
Y_test_ridge_ur = pd.DataFrame(Y_test_ridge_ur, columns=['Y Test Ridge'])
Y_test_ridge_ur
Y_test_ridge_ur.reset_index(drop=True, inplace=True)
Y_test_ridge_ur.head()

   Y Test Ridge
0      7.937064
1      6.435363
2      6.736018
3      7.205222
4      6.682854

In [19]:
y_test = pd.DataFrame(y_test, columns=['log(Total Spend/capita)'])
y_test.reset_index()
y_test.reset_index(drop=True, inplace=True)
y_test.head()

   log(Total Spend/capita)
0                 9.011916
1                 6.485500
2                 7.130928
3                 7.928423
4                 7.178477

In [20]:
data = pd.concat([y_test,Y_test_ridge_ur],axis=1)
data['true percentile'] = data['log(Total Spend/capita)'].rank(ascending = True)/data['log(Total Spend/capita)'].rank(ascending = True).max()
data['predicted percentile'] = data['Y Test Ridge'].rank(ascending = True)/data['Y Test Ridge'].rank(ascending = True).max()
data['exclusion error'] = np.nan
data.loc[data['true percentile'] <= 0.5, data['exclusion error']] = 0
data.loc[((data['true percentile'] <= 0.5) & (data['predicted percentile'] > 0.5)), data['exclusion error']] = 1
data[np.nan].mean()

0.25

In [21]:
data_ur = pd.concat([y_test,Y_test_ridge_ur],axis=1)


data_ur['true percentile'] = data_ur['log(Total Spend/capita)'].rank(ascending = True)/data_ur['log(Total Spend/capita)'].rank(ascending = True).max()
data_ur['predicted percentile'] = data_ur['Y Test Ridge'].rank(ascending = True)/data_ur['Y Test Ridge'].rank(ascending = True).max()
data_ur['exclusion error'] = np.nan
data_ur.loc[data_ur['true percentile'] <= 0.25, data_ur['exclusion error']] = 0
data_ur.loc[((data_ur['true percentile'] <= 0.25) & (data_ur['predicted percentile'] > 0.25)), data_ur['exclusion error']] = 1
data_ur[np.nan].mean()

0.47058823529411764

In [22]:
#inclusion error
data_ur['true percentile'] = data_ur['log(Total Spend/capita)'].rank(ascending = True)/data_ur['log(Total Spend/capita)'].rank(ascending = True).max()
data_ur['predicted percentile'] = data_ur['Y Test Ridge'].rank(ascending = True)/data_ur['Y Test Ridge'].rank(ascending = True).max()
data_ur['inclusion error'] = np.nan
data_ur.loc[data_ur['predicted percentile'] <= 0.5, data_ur['inclusion error']] = 0
data_ur.loc[((data_ur['predicted percentile'] <= 0.5) & (data_ur['true percentile'] > 0.5)), data_ur['inclusion error']] = 1
data_ur[np.nan].mean()

0.31543624161073824